### ISSUE TITLE
ModuleNotFoundError: No module named 'transform3d'

### ISSUE THREAD

**Issue by MattiaDeiRossi** [neobotix/elite-robots2#56]
Hi all ,

Testing this workspace inside `ros:humble-ros-base` docker container, after installing and sourcing all requirements and runnning the command:

```
ros2 launch elite_arm_driver bringup.launch.py
```

There is an error:
```
root@mattia-Latitude-5510:/ros_workspace# ros2 launch elite_arm_driver bringup.launch.py
[INFO] [launch]: All log files can be found below /root/.ros/log/2023-08-02-14-00-25-177678-mattia-Latitude-5510-3116
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [elite-1]: process started with pid [3118]
[INFO] [robot_state_publisher-2]: process started with pid [3120]
[robot_state_publisher-2] [INFO] [1690984825.355762654] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1690984825.356271447] [robot_state_publisher]: got segment flan
[robot_state_publisher-2] [INFO] [1690984825.356519259] [robot_state_publisher]: got segment link1
[robot_state_publisher-2] [INFO] [1690984825.356747381] [robot_state_publisher]: got segment link2
[robot_state_publisher-2] [INFO] [1690984825.356962983] [robot_state_publisher]: got segment link3
[robot_state_publisher-2] [INFO] [1690984825.357174809] [robot_state_publisher]: got segment link4
[robot_state_publisher-2] [INFO] [1690984825.357383702] [robot_state_publisher]: got segment link5
[robot_state_publisher-2] [INFO] [1690984825.357592627] [robot_state_publisher]: got segment link6
[robot_state_publisher-2] [INFO] [1690984825.357797080] [robot_state_publisher]: got segment world
[elite-1] Traceback (most recent call last):
[elite-1]   File "/ros_workspace/install/elite_arm_driver/lib/elite_arm_driver/elite", line 33, in <module>
[elite-1]     sys.exit(load_entry_point('elite-arm-driver', 'console_scripts', 'elite')())
[elite-1]   File "/ros_workspace/install/elite_arm_driver/lib/elite_arm_driver/elite", line 25, in importlib_load_entry_point
[elite-1]     return next(matches).load()
[elite-1]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[elite-1]     module = import_module(match.group('module'))
[elite-1]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[elite-1]     return _bootstrap._gcd_import(name[level:], package, level)
[elite-1]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[elite-1]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[elite-1]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[elite-1]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[elite-1]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[elite-1]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[elite-1]   File "/ros_workspace/build/elite_arm_driver/elite_arm_driver/elite_driver_node.py", line 11, in <module>
[elite-1]     from .elite_arm_kinematics import EliteArmKinematics
[elite-1]   File "/ros_workspace/build/elite_arm_driver/elite_arm_driver/elite_arm_kinematics.py", line 4, in <module>
[elite-1]     import transform3d as tfs
[elite-1] ModuleNotFoundError: No module named 'transform3d'
[ERROR] [elite-1]: process has died [pid 3118, exit code 1, cmd '/ros_workspace/install/elite_arm_driver/lib/elite_arm_driver/elite --ros-args --params-file /tmp/launch_params_t2q1lopw'].

```

But command 
```
root@mattia-Latitude-5510:/ros_workspace# pip3 install elirobots transforms3d pytest rosdepc
```
show me that libraries are installed correctly
```
Requirement already satisfied: elirobots in /usr/local/lib/python3.10/dist-packages (0.0.6)
Requirement already satisfied: transforms3d in /usr/local/lib/python3.10/dist-packages (0.4.1)
Requirement already satisfied: pytest in /usr/lib/python3/dist-packages (6.2.5)
Requirement already satisfied: rosdepc in /usr/local/lib/python3.10/dist-packages (1.0.2)
Requirement already satisfied: loguru>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from elirobots) (0.7.0)
Requirement already satisfied: rosdep in /usr/lib/python3/dist-packages (from rosdepc) (0.22.2)
Requirement already satisfied: PyYAML>=3.1 in /usr/lib/python3/dist-packages (from rosdep->rosdepc) (5.4.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from rosdep->rosdepc) (59.6.0)
```

Do you have any suggestions?

**Comment by padhupradheep** [comment]
Thanks for reporting. Could you please try once again?

**Comment by MattiaDeiRossi** [comment]
Hi, 

Finally I installed humble on Xubuntu 22 and got another error launching `ros2 launch elite_arm_driver bringup.launch.py`:

```
mattia@mattia-Latitude-5510:~/elite_ros2_ws$ ros2 launch elite_arm_driver bringup.launch.py
[INFO] [launch]: All log files can be found below /home/mattia/.ros/log/2023-08-04-13-42-51-141161-mattia-Latitude-5510-30923
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [elite-1]: process started with pid [30935]
[INFO] [robot_state_publisher-2]: process started with pid [30937]
[robot_state_publisher-2] [INFO] [1691149372.088162297] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1691149372.138639961] [robot_state_publisher]: got segment flan
[robot_state_publisher-2] [INFO] [1691149372.140705278] [robot_state_publisher]: got segment link1
[robot_state_publisher-2] [INFO] [1691149372.142165795] [robot_state_publisher]: got segment link2
[robot_state_publisher-2] [INFO] [1691149372.142750984] [robot_state_publisher]: got segment link3
[robot_state_publisher-2] [INFO] [1691149372.143146518] [robot_state_publisher]: got segment link4
[robot_state_publisher-2] [INFO] [1691149372.144477865] [robot_state_publisher]: got segment link5
[robot_state_publisher-2] [INFO] [1691149372.145045515] [robot_state_publisher]: got segment link6
[robot_state_publisher-2] [INFO] [1691149372.145501248] [robot_state_publisher]: got segment world
[elite-1] [INFO] [1691149373.731811498] [elite_driver_node]: Listening for kinematics request
[elite-1] [INFO] [1691149373.866086003] [elite_driver_node]: ready to move arm
[elite-1] [INFO] [1691149373.890057378] [elite_driver_node]: starting elite arm set IO
[elite-1] [INFO] [1691149373.895946068] [elite_driver_node]: starting elite state publishers
[elite-1] [INFO] [1691149373.934838376] [elite_driver_node]: starting elite arm trajectory action
[elite-1] Traceback (most recent call last):
[elite-1]   File "/home/mattia/elite_ros2_ws/install/elite_arm_driver/lib/elite_arm_driver/elite", line 33, in <module>
[elite-1]     sys.exit(load_entry_point('elite-arm-driver', 'console_scripts', 'elite')())
[elite-1]   File "/home/mattia/elite_ros2_ws/build/elite_arm_driver/elite_arm_driver/elite_driver_node.py", line 73, in main
[elite-1]     elite_driver.init_ec_sdk()
[elite-1]   File "/home/mattia/elite_ros2_ws/build/elite_arm_driver/elite_arm_driver/elite_driver_node.py", line 52, in init_ec_sdk
[elite-1]     self.elite_robot = EC(
[elite-1]   File "/home/mattia/.local/lib/python3.10/site-packages/elite/_ec.py", line 39, in __init__
[elite-1]     self._log_init(self.robot_ip)
[elite-1]   File "/home/mattia/.local/lib/python3.10/site-packages/elite/_baseec.py", line 48, in _log_init
[elite-1]     self.logger = Logger(core=Core(), exception=None, depth=0, record=False, lazy=False, colors=False,
[elite-1] TypeError: Logger.__init__() got an unexpected keyword argument 'patcher'
[ERROR] [elite-1]: process has died [pid 30935, exit code 1, cmd '/home/mattia/elite_ros2_ws/install/elite_arm_driver/lib/elite_arm_driver/elite --ros-args --params-file /tmp/launch_params_aeq8cpe5'].
```

**Comment by padhupradheep** [comment]
Thanks for reporting the issue @MattiaDeiRossi 

This issue is deep rooted in the @Elite-Robots SDK. 

According to the logs, there is no argument called `patcher` for the [Logger class initializiation from loguru](https://github.com/neobotix/eliterobot/blob/9ec5486e57b5abce43cacd8271a5791f9d409ba1/elite/_baseec.py#L51). I looked into the [source code of the Logger class](https://github.com/Delgan/loguru/blob/d17ae011117e46365f3b68ec4eded733b8434090/loguru/_logger.py#L231) and found that, it's just a typo. `patcher` should be replaced with `patches`.

**Comment by JunJie-zhang-o** [comment]
Please check loguru's version is 0.6.0

You can try the following command

pip3 uninstall loguru

pip3 install loguru==0.6.0

**Comment by padhupradheep** [comment]
Thanks for the answer @JunJie-zhang-o . By default when we install `elirobots`, it installs that latest version of `loguru`. Is it possible to set the rule in the requirements to `0.6.0`?

Thanks once again.

**Comment by JunJie-zhang-o** [comment]
yes ，I will update requirements.txt and republish the new version. thanks for feedback.

**Comment by padhupradheep** [comment]
@MattiaDeiRossi could you please do the update @JunJie-zhang-o as pointed out ? This should definitely work. Feel free to close the issue there after. 

If you have anyother issue, please open a new one, that would be real nice. Thanks!

**Comment by padhupradheep** [comment]
@MattiaDeiRossi feel free to continue the thread, if you still face the issue.
